# MiniCanvas Render Deployment Configuration
# Note: This configuration requires manual environment variable setup
# due to Render's service linking limitations

services:
  # HTTP Backend API
  - type: web
    name: minicanvas-http-backend
    env: node
    plan: starter
    buildCommand: "cd apps/http-backend && npm install && npm run build"
    startCommand: "cd apps/http-backend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      # DATABASE_URL will be set manually after PostgreSQL creation

  # WebSocket Backend
  - type: web
    name: minicanvas-ws-backend
    env: node
    plan: starter
    buildCommand: "cd apps/ws-backend && npm install && npm run build"
    startCommand: "cd apps/ws-backend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # JWT_SECRET and DATABASE_URL will be set manually

  # Next.js Frontend
  - type: web
    name: minicanvas-frontend
    env: node
    plan: starter
    buildCommand: "cd apps/minicanvas-fe && npm install && npm run build"
    startCommand: "cd apps/minicanvas-fe && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      # HTTP_BACKEND_URL and WS_BACKEND_URL will be set manually